### PR TITLE
Match any sf/sfc object for #97

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @agila5 this is what I meant in my comment in #166 - could have explained in words but easier as a PR. Results (should work with any sf/sfc object):

``` r
# packages
remotes::install_github("itsleeds/osmextract", "match-sf")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'osmextract' from a github remote, the SHA1 (0e8db75b) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(osmextract)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright.
#> Check the package website, itsleeds.github.io/osmextract for more details.

# a random LINESTRING in Leeds
linestring_chapeltown <- st_sfc(
  st_linestring(
    rbind(c(-1.549077, 53.800755), c(-1.560897, 53.810830))
  ), 
  crs = 4326
)
oe_match(linestring_chapeltown)
#> although coordinates are longitude/latitude, st_contains assumes that they are planar
#> The input place was matched with multiple geographical areas. Selecting the areas with the highest "level". See the help page associated to the chosen provider for an explanation of the meaning of the "level" field.
#> $url
#> [1] "https://download.geofabrik.de/europe/great-britain/england/west-yorkshire-latest.osm.pbf"
#> 
#> $file_size
#> [1] 32270118

linestring_uk_italy <- st_sfc(
  st_linestring(
    rbind(c(-1.549077, 53.800755), c(11, 45))
  ), 
  crs = 4326
)
oe_match(linestring_uk_italy)
#> although coordinates are longitude/latitude, st_contains assumes that they are planar
#> $url
#> [1] "https://download.geofabrik.de/europe-latest.osm.pbf"
#> 
#> $file_size
#> [1] 23245241740
```

<sup>Created on 2021-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Note that

```r
    matched_zones = provider_data[place, op = sf::st_contains]
```

Returns only objects that *entirely contain* the place.

**Comment by Robinlovelace** [comment]
Another advantage of this approach, after the latest commit above it also allows selection of provider regions that contain multi-feature sf objects such as `spData:lnd`:

``` r
# packages
remotes::install_github("itsleeds/osmextract", "match-sf")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'osmextract' from a github remote, the SHA1 (fb88c700) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(osmextract)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright.
#> Check the package website, itsleeds.github.io/osmextract for more details.

oe_match(spData::lnd)
#> although coordinates are longitude/latitude, st_contains assumes that they are planar
#> The input place was matched with multiple geographical areas. Selecting the areas with the highest "level". See the help page associated to the chosen provider for an explanation of the meaning of the "level" field.
#> $url
#> [1] "https://download.geofabrik.de/europe/great-britain/england/greater-london-latest.osm.pbf"
#> 
#> $file_size
#> [1] 59746355
```

<sup>Created on 2021-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by agila5** [comment]
So this should replace #166? Do you know why tests fail? If not I can check it tomorrow. btw: I think that the best approach would be creating an `sfc` method and an `sf` methods which is just `oe_match(sf::st_geometry(place), ...)` instead of an if clause in the default method.

**Comment by Robinlovelace** [comment]
> So this should replace #166?

Yes that's the plan. I think the approach can achieve the same aims and more (including returning Europe for a place that goes from the UK to Italy : ) with fewer lines of code. Not sure why it's failing. Also not sure whether it's more time efficient to work on this or simply for you to port the approach across from here into #166, this line in particular (which was also at one point in the codebase when the package was called `geofabrik`):

https://github.com/ITSLeeds/osmextract/blob/fb88c7003ab8982bd36c2dfb974993b04246ff8f/R/match.R#L131

**Comment by agila5** [comment]
Ok, thanks for the fix. I think that the easier approach is to close this PR and merge the ideas into the other ones, then again merge into the PR for `level` argument and finally merge into the master branch. I will complete all steps tomorrow morning!

**Pull request closed without merging**
